# Generated by Django 4.0.4 on 2023-05-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trigger_app", "0018_alter_cometlog_log_alter_event_lvc_event_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cometlog",
            name="log",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="lvc_event_url",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="lvc_skymap_fits",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="observations",
            name="reason",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="observations",
            name="website_link",
            field=models.URLField(max_length=1024),
        ),
    ]
