# Generated by Django 4.0.4 on 2023-05-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trigger_app", "0019_alter_cometlog_log_alter_event_lvc_event_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="lvc_significance",
        ),
        migrations.RemoveField(
            model_name="proposalsettings",
            name="observe_low_significance",
        ),
        migrations.AddField(
            model_name="event",
            name="lvc_significant",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
