# Generated by Django 4.0.4 on 2023-05-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0022_alter_proposalsettings_mwa_freqspecs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telescopeprojectid',
            name='password',
            field=models.CharField(help_text='The project password for the telescope used to automatically schedule observations.', max_length=2020, verbose_name='Telescope Project Password'),
        ),
    ]
