# Generated by Django 4.0.4 on 2023-06-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trigger_app", "0025_event_lvc_instruments_observations_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="lvc_false_alarm_rate",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
