# Generated by Django 4.0.4 on 2023-08-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trigger_app", "0029_observations_mwa_sky_map_pointings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observations",
            name="mwa_sky_map_pointings",
            field=models.ImageField(blank=True, null=True, upload_to="mwa_pointings/"),
        ),
    ]
