# Generated by Django 4.0.4 on 2023-08-01 08:21

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trigger_app", "0030_alter_observations_mwa_sky_map_pointings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observations",
            name="mwa_sky_map_pointings",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/media/mwa_pointings"
                ),
                upload_to="",
            ),
        ),
    ]
