# Generated by Django 4.0.4 on 2023-08-17 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trigger_app", "0036_alter_proposalsettings_testing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="observations",
            old_name="obsid",
            new_name="trigger_id",
        ),
    ]
