# Generated by Django 4.0.4 on 2023-10-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0037_rename_obsid_observations_trigger_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATCAUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('httpAuthUsername', models.CharField(max_length=128)),
                ('httpAuthPassword', models.CharField(max_length=128)),
            ],
        ),
    ]
