# Generated by Django 4.0.4 on 2023-11-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trigger_app", "0038_atcauser"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposalsettings",
            name="early_observation_time_seconds",
            field=models.IntegerField(
                default=900,
                help_text="This is the observation time for early warning warnings, for MWA will use n=1",
            ),
        ),
        migrations.AddField(
            model_name="proposalsettings",
            name="maximum_observation_time_minutes",
            field=models.IntegerField(
                default=0,
                help_text="Set maximum observation time based off event time e.g. event 30 min ago when set to 120 will only allow a max observation of 90 mins with events older than 120 mins will be ignored. Setting to 0 disables this check",
            ),
        ),
    ]
