# Generated by Django 5.1 on 2024-11-24 13:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0043_remove_proposalsettings_antares_min_ranking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsettings',
            name='streams',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='List of streams for this proposal', size=None),
        ),
        migrations.AddField(
            model_name='proposalsettings',
            name='version',
            field=models.CharField(default='1.0.0', help_text='Version of the proposal settings', max_length=10, null=True),
        ),
    ]
