# Generated by Django 5.1 on 2024-11-25 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0044_proposalsettings_streams_proposalsettings_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Time when this proposal was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposalsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time this proposal was updated'),
        ),
    ]
