# Generated by Django 5.1 on 2024-11-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0045_proposalsettings_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldecision',
            name='version',
            field=models.CharField(default='1.0.0', help_text='Version inherited from ProposalSettings', max_length=10, null=True),
        ),
    ]
