# Generated by Django 5.1 on 2024-11-25 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0046_proposaldecision_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observations',
            name='proposal_decision_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trigger_app.proposaldecision'),
        ),
        migrations.AlterField(
            model_name='proposaldecision',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trigger_app.proposalsettings'),
        ),
    ]
