# Generated by Django 5.1 on 2024-11-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trigger_app', '0048_proposalsettingsarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsettings',
            name='code_link',
            field=models.CharField(blank=True, default='', help_text='Link to the code repository or documentation', max_length=2028, null=True),
        ),
        migrations.AddField(
            model_name='proposalsettingsarchive',
            name='code_link',
            field=models.CharField(blank=True, default='', help_text='Link to the code repository or documentation', max_length=2028, null=True),
        ),
    ]
